"""again add failed

Revision ID: 3035952ce187
Revises: fc5bf3bdbb25
Create Date: 2026-04-26 21:18:49.365237

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3035952ce187"
down_revision: Union[str, Sequence[str], None] = "fc5bf3bdbb25"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE inboxstatusenum ADD VALUE IF NOT EXISTS 'FAILED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
