"""add unique to idempotency

Revision ID: 6f395445564c
Revises: 8ae21b37ea1a
Create Date: 2026-04-24 13:41:26.471741

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6f395445564c"
down_revision: Union[str, Sequence[str], None] = "8ae21b37ea1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "orders", ["idempotency_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "orders", type_="unique")
    # ### end Alembic commands ###
