"""added retry to inbox

Revision ID: a4f99041ad1e
Revises: d8c5403ff251
Create Date: 2026-04-26 16:52:22.270272

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "a4f99041ad1e"
down_revision: Union[str, Sequence[str], None] = "d8c5403ff251"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE inboxstatusenum_new AS ENUM ('PENDING', 'COMPLETED', 'FAILED')"
    )
    op.execute(
        """
        ALTER TABLE inbox
        ALTER COLUMN status TYPE inboxstatusenum_new
        USING (
            CASE lower(status::text)
                WHEN 'pending' THEN 'PENDING'::inboxstatusenum_new
                WHEN 'completed' THEN 'COMPLETED'::inboxstatusenum_new
                WHEN 'failed' THEN 'FAILED'::inboxstatusenum_new
                ELSE 'PENDING'::inboxstatusenum_new
            END
        )
        """
    )
    # 3) Удаляем старый тип и переименовываем новый
    op.execute("DROP TYPE inboxstatusenum")
    op.execute("ALTER TYPE inboxstatusenum_new RENAME TO inboxstatusenum")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE inboxstatusenum_old AS ENUM ('pending', 'completed', 'failed')"
    )
    op.execute(
        """
        ALTER TABLE inbox
        ALTER COLUMN status TYPE inboxstatusenum_old
        USING (
            CASE status::text
                WHEN 'PENDING' THEN 'pending'::inboxstatusenum_old
                WHEN 'COMPLETED' THEN 'completed'::inboxstatusenum_old
                WHEN 'FAILED' THEN 'failed'::inboxstatusenum_old
                ELSE 'pending'::inboxstatusenum_old
            END
        )
        """
    )
    op.execute("DROP TYPE inboxstatusenum")
    op.execute("ALTER TYPE inboxstatusenum_old RENAME TO inboxstatusenum")
    # ### end Alembic commands ###
