"""added retry to inbox

Revision ID: a4f99041ad1e
Revises: d8c5403ff251
Create Date: 2026-04-26 16:52:22.270272

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4f99041ad1e"
down_revision: Union[str, Sequence[str], None] = "d8c5403ff251"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE inboxstatusenum ADD VALUE IF NOT EXISTS 'failed'")
    op.add_column(
        "inbox", sa.Column("retry", sa.Integer(), nullable=False, server_default="0")
    )
    op.alter_column("inbox", "retry", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("inbox", "retry")
    # ### end Alembic commands ###
