"""fix inbox

Revision ID: d8c5403ff251
Revises: 348632f32d1e
Create Date: 2026-04-25 14:13:30.075501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d8c5403ff251"
down_revision: Union[str, Sequence[str], None] = "348632f32d1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "inbox", ["id"])
    op.drop_column("inbox", "event_id")
    op.create_unique_constraint(None, "outbox", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "outbox", type_="unique")
    op.add_column(
        "inbox",
        sa.Column("event_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "inbox", type_="unique")
    # ### end Alembic commands ###
