"""fix enum

Revision ID: fc5bf3bdbb25
Revises: a4f99041ad1e
Create Date: 2026-04-26 20:40:16.722019

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "fc5bf3bdbb25"
down_revision: Union[str, Sequence[str], None] = "a4f99041ad1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
