import os
import dotenv

dotenv.load_dotenv()

# Capashino
STORAGE_BASE_URL = os.getenv("STORAGE_BASE_URL")
STORAGE_API_KEY = os.getenv("STORAGE_API_KEY")

PAYMENT_BASE_URL = os.getenv("PAYMENT_BASE_URL")
PAYMENT_API_KEY = os.getenv("PAYMENT_API_KEY")
PAYMENT_CALLBACK_URL = os.getenv("PAYMENT_CALLBACK_URL")

NOTIFICATION_BASE_URL = os.getenv("NOTIFICATION_BASE_URL")
NOTIFICATION_API_KEY = os.getenv("NOTIFICATION_API_KEY")


# PostgreSQL
POSTGRES_CONNECTION_STRING = os.getenv("POSTGRES_CONNECTION_STRING")

# Kafka
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS")
